enum {


	IDS_TAG_DELTAMUSH = 1000,
	IDS_DELTAMUSH_DEFORMER,
	ID_TDELTAMUSH_OBJECT_MEM_SIZE, 
	ID_TDELTAMUSH_AUTOMODE,
	ID_DELTAMUSH_VERSION,
	ID_DELTAMUSH_ADDBOTH,
	ID_DELTAMUSH_ADDBOTH_STRING,
    __avoid_alert_


};