CONTAINER TDeltamushres
{
	NAME TDeltamushres;
	INCLUDE Texpression;

	GROUP ID_TAGPROPERTIES
	{

		GROUP {	
			COLUMNS 2;
			BUTTON ID_TDELTAMUSH_OBJECT_INITIAL { }
			BUTTON ID_TDELTAMUSH_OBJECT_RESTORE {}
		}
		

		STATICTEXT    ID_TDELTAMUSH_OBJECT_MEM {}

		BOOL ID_TDELTAMUSH_PREV_SMOOTH{}
		BOOL ID_TDELTAMUSH_PIN_CORNER{}
		
		REAL ID_TDELTAMUSH_WEIGHT {CUSTOMGUI REALSLIDER; MIN 0.0; MAX 1.0; MINSLIDER 0.0;MAXSLIDER 1.0 ; STEP 0.05; UNIT REAL;}
		LONG ID_TDELTAMUSH_WEIGHT_TYPE
		{
			CYCLE {
				ID_TDELTAMUSH_WEIGHT_FIXE;
				ID_TDELTAMUSH_WEIGHT_PROPORTIONNNEL;
			
			}
		}

		LONG ID_TDELTAMUSH_SMOOTH_ITERATION {CUSTOMGUI LONGSLIDER; MIN 0; MAX 200;MINSLIDER 0 ;MAXSLIDER 100 ; STEP 1;}

		LINK ID_TDELTAMUSH_WEIGHTMAP
		{

			ACCEPT { 5682; }

		}

	}
	
	



}
