#ifndef _T_DELTA_MUSH_RES_
#define _T_DELTA_MUSH_RES_


enum {

		ID_TDELTAMUSH_OBJECT_INITIAL = 1000,
        ID_TDELTAMUSH_OBJECT_RESTORE,
        ID_TDELTAMUSH_OBJECT_MEM,
        ID_TDELTAMUSH_WEIGHT_TYPE,
        ID_TDELTAMUSH_SMOOTH_ITERATION,
        ID_TDELTAMUSH_PIN_CORNER,
        ID_TDELTAMUSH_PREV_SMOOTH,
        ID_TDELTAMUSH_WEIGHTMAP,
        ID_TDELTAMUSH_WEIGHT,
        


    //////
        ID_TDELTAMUSH_WEIGHT_FIXE = 0 ,
        ID_TDELTAMUSH_WEIGHT_PROPORTIONNNEL,








	__DUMMY_ELEMENT__T_SHOW_TBN_



};

#endif